# Generated by Django 2.2.13 on 2021-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(blank=True, default='', max_length=5000)),
                ('init_message', models.CharField(blank=True, default='', max_length=5000)),
                ('variable_state', models.CharField(blank=True, default='', max_length=5000)),
                ('ResidenceZip', models.CharField(blank=True, default='', max_length=100)),
                ('ResidenceCity', models.CharField(blank=True, default='', max_length=100)),
                ('ResidenceState', models.CharField(default=True, max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('token', models.CharField(default='d3a1b634-90a7-eb11-a963-005056a96ce9', max_length=40)),
                ('flowchart3_stucked_status', models.BooleanField(default=False)),
                ('ReservationUserCode', models.CharField(blank=True, default='', max_length=100)),
                ('ReservationClientCode', models.CharField(blank=True, default='', max_length=100)),
                ('ReservationVendorCode', models.CharField(blank=True, default='', max_length=100)),
                ('ReservationAgentCode', models.CharField(blank=True, default='', max_length=100)),
                ('TribalEligible', models.CharField(blank=True, default='', max_length=100)),
                ('FcraDisclosureText', models.CharField(blank=True, default='', max_length=1000)),
                ('FcraAdditionalDisclosureText', models.CharField(blank=True, default='', max_length=1000)),
                ('FcraAcknowledgement', models.CharField(blank=True, default='', max_length=1000)),
                ('EligibiltyPrograms', models.CharField(blank=True, default='', max_length=100)),
                ('OrderNumber', models.CharField(blank=True, default=0, max_length=100)),
                ('PackageId', models.CharField(blank=True, default='', max_length=100)),
                ('TribalResident', models.BooleanField(default=False)),
                ('program', models.CharField(blank=True, default='', max_length=100)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('second_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('suffix', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
                ('last_four_social', models.CharField(blank=True, default='', max_length=100)),
                ('residential_address', models.CharField(blank=True, default='', max_length=100)),
                ('apt_unit1', models.CharField(blank=True, default='', max_length=100)),
                ('apt_unit2', models.CharField(blank=True, default='', max_length=100)),
                ('is_permanent', models.BooleanField(default=True)),
                ('address_nature', models.CharField(blank=True, default='', max_length=100)),
                ('form_filled', models.BooleanField(default=False)),
                ('shipping_address', models.CharField(blank=True, default='', max_length=100)),
                ('form_zip_code', models.CharField(blank=True, default='', max_length=100)),
                ('ServicePlan', models.CharField(blank=True, default='', max_length=30)),
                ('iehBool', models.BooleanField(default=False)),
                ('benefit_code', models.CharField(default='', max_length=10)),
                ('zap_acct', models.CharField(default='', max_length=10)),
                ('zap_name', models.CharField(default='', max_length=10)),
                ('sequence_count', models.CharField(default='0', max_length=5)),
                ('islifeline_service', models.CharField(blank=True, default='', max_length=20)),
                ('other_adult', models.CharField(blank=True, default='', max_length=20)),
                ('share_liveing_expesses', models.CharField(blank=True, default='', max_length=20)),
                ('PhoneNumber', models.CharField(blank=True, default='', max_length=10)),
                ('PinCode', models.CharField(blank=True, default='', max_length=4)),
                ('BestWayToReachYou', models.CharField(blank=True, default='', max_length=10)),
                ('ApplicationStatus', models.CharField(blank=True, default='', max_length=50)),
                ('Check_NVEligibility_url', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('sequence_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=40)),
            ],
        ),
    ]
