# Generated by Django 3.2.6 on 2021-08-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattracker',
            name='Income',
            field=models.IntegerField(default=0),
        ),
    ]
